# services:
#   postgres:
#     image: postgres:13
#     container_name: postgres_db
#     environment:
#       POSTGRES_DB: postgres
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#     ports:
#       - '5432:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:

services:
  app:
    image: nikhildhamecha19888/todo-node
    build: .
    ports:
      - 4000:4000
    environment:
      PORT: 4000
      NODE_ENV: development
    volumes:
      - .:/app
