name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Docker compose up
        run: docker-compose up --build
