# name: Deploy Node Application

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Source
#         uses: action/checkout@v4
#       - name: Login to docker hub
#         run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD}}
#       - name: Build Docker Image
#         run: docker build -t nikhildhamecha19888/todo-node
#       - name: Publish Image to docker hub
#         run: docker push nikhildhamecha19888/todo-node:latest

#     deploy:
#       needs: build
#       runs-on: self-hosted
#       steps:
#         - name: Pull image from docker hub
#           run: docker pull nikhildhamecha19888/todo-node:latest
#         - name: Run Docker Container
#           run: docker run -d -p 4000:4000 --name todo-node-container

name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t nikhildhamecha19888/todo-node:latest .

      - name: Publish Image to docker hub
        run: docker push nikhildhamecha19888/todo-node:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull nikhildhamecha19888/todo-node:latest

      - name: Run Docker Container
        run: docker run -d -p 4000:4000 --name todo-node-container nikhildhamecha19888/todo-node:latest
